# uncompyle6 version 3.5.1
# Python bytecode 2.7 (62211)
# Decompiled from: Python 3.6.5 (default, Apr 19 2019, 17:01:24) 
# [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]
# Embedded file name: ../src\config\Config.py
# Compiled at: 2019-03-17 23:12:45
u"""
Created on 2018年4月17日

@author: mes
"""
import ConfigParser, os, sys
curPath = os.path.abspath(os.path.dirname(__file__))
rootPath = os.path.split(curPath)[0]
sys.path.append(rootPath)
conf = ConfigParser.ConfigParser()
conf.read('../config/config.ini')
webIP = conf.get('web', 'webIP')
webPORT = conf.get('web', 'webPORT')
host = conf.get('sql', 'host')
user = conf.get('sql', 'user')
passwd = conf.get('sql', 'passwd')
db = conf.get('sql', 'db')
dbcharset = conf.get('sql', 'dbcharset')
dbport = conf.get('sql', 'dbport')
txsPath = conf.get('filePath', 'listenTxsPath')
internetPath = conf.get('filePath', 'listenInternetPath')
extractFilePath = conf.get('filePath', 'extractFilePath')
localBasePath = conf.get('filePath', 'localBasePath')
jsfwPath = conf.get('filePath', 'jsfwPath')
jsfwExtractFilePath = conf.get('filePath', 'jsfwExtractFilePath')
zyfwFileBasePath = conf.get('filePath', 'zyfwFileBasePath')
anTianSecurityPath = conf.get('filePath', 'anTianSecurityPath')
anTianSecurityExtractFilePath = conf.get('filePath', 'anTianSecurityExtractFilePath')
insertSqlPers = conf.get('sqlPers', 'InternetInsertSqlPers')
jsfwInsertSqlPers = conf.get('sqlPers', 'jsfwInsertSqlPers')
txsInsertSqlPers = conf.get('sqlPers', 'txsInsertSqlPers')
zyfwInsertSqlPers = conf.get('sqlPers', 'zyfwInsertSqlPers')
xhsInsertSqlPers = conf.get('sqlPers', 'xhsInsertSqlPers')
digitLibInsertSqlPers = conf.get('sqlPers', 'digitLibInsertSqlPers')
anTianSecurityInsertSqlPers = conf.get('sqlPers', 'anTianSecurityInsertSqlPers')
redis_pwd = conf.get('redis', 'redis_pwd')
redis_ip = conf.get('redis', 'redis_ip')
digitLib_all_DB = conf.get('library', 'digitLib_all_DB')
digitLib_db_info = conf.get('library', 'digitLib_db_info')
digitLib_db_pic = conf.get('library', 'digitLib_db_pic')
digitLib_db_file = conf.get('library', 'digitLib_db_file')
digitLib_timeout = conf.get('library', 'digitLib_timeout')
internetSpider = conf.get('source', 'internetSpider')
digitLibSpider = conf.get('source', 'digitLibSpider')
txsSpider = conf.get('source', 'txsSpider')
jsfwSpider = conf.get('source', 'jsfwSpider')
videoSpider = conf.get('source', 'videoSpider')
zyfwSpider = conf.get('source', 'zyfwSpider')
xhsSpider = conf.get('source', 'xhsSpider')
anTianSecuritySpider = conf.get('source', 'anTianSecuritySpider')
video_list_path = conf.get('video', 'video_list_path')
video_base_url = conf.get('video', 'video_base_url')
video_postfix_path = conf.get('video', 'video_postfix_path')
video_spider_start_time = conf.get('video', 'video_spider_start_time')
zyfw_host = conf.get('zyfw', 'zyfw_host')
zyfw_user = conf.get('zyfw', 'zyfw_user')
zyfw_passwd = conf.get('zyfw', 'zyfw_passwd')
zyfw_db = conf.get('zyfw', 'zyfw_db')
zyfw_dbcharset = conf.get('zyfw', 'zyfw_dbcharset')
format = conf.get('log', 'format')
backupcount = conf.get('log', 'backupcount')
maxbytes = conf.get('log', 'maxbytes')
level = conf.get('log', 'level')
logBasePath = conf.get('log', 'logBasePath')
isIndex = conf.get('solr', 'isIndex')
divisionNum = conf.get('division', 'divisionNum')
if __name__ == '__main__':
    print rootPath